In [25]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd

# API 엔드포인트 URL
url = "https://apis.data.go.kr/1220000/Itemtrade/getItemtradeList"

# 공통된 파라미터
service_key = "IFpPHZ4Gvx6iHNB7PPjpbp5scGLYgzJM66nR4RDKH5XLk0WrlDW1RFe1EgaqDFscTWQ4nF1b4aJE/sOpxadeqA=="
hs_sgn = "5001000000"

# 빈 DataFrame 생성
df = pd.DataFrame()

# 2001년부터 2023년까지 데이터 수집
for year in range(2001, 2024):
    strt_yymm = f"{year}01"
    end_yymm = f"{year}12"
    
    # 요청에 필요한 파라미터
    params = {
        "serviceKey": service_key,
        "strtYymm": strt_yymm,
        "endYymm": end_yymm,
        "hsSgn": hs_sgn
    }

    # GET 요청 보내기
    response = requests.get(url, params=params)

    # 응답 상태 코드와 텍스트 출력
    print(f"응답 상태 코드 ({year}):", response.status_code)

    # 응답 텍스트를 XML 파싱하기
    try:
        root = ET.fromstring(response.content)
        print(f"XML 파싱 성공 ({year})")
        
        # 응답 헤더에서 결과 코드와 메시지 출력
        result_code = root.findtext('.//resultCode')
        result_msg = root.findtext('.//resultMsg')
        print(f"결과 코드 ({year}):", result_code)
        print(f"결과 메시지 ({year}):", result_msg)
        
        # 항목들을 파싱하여 DataFrame으로 변환
        items = root.findall('.//item')
        data = []
        for item in items:
            bal_payments = item.findtext('balPayments')
            exp_dlr = item.findtext('expDlr')
            exp_wgt = item.findtext('expWgt')
            hs_code = item.findtext('hsCode')
            imp_dlr = item.findtext('impDlr')
            imp_wgt = item.findtext('impWgt')
            stat_kor = item.findtext('statKor')
            year = item.findtext('year')
            
            data.append({
                "년도": year,
                "HS 코드": hs_code,
                "품목": stat_kor,
                "수출 달러": exp_dlr,
                "수출 무게": exp_wgt,
                "수입 달러": imp_dlr,
                "수입 무게": imp_wgt,
                "수지": bal_payments
            })
        
        # 연도별 데이터프레임을 메인 데이터프레임에 추가
        year_df = pd.DataFrame(data)
        df = pd.concat([df, year_df], ignore_index=True)
        
    except ET.ParseError:
        print(f"XML 파싱 실패 ({year})")

# 최종 DataFrame 출력
print(df)

응답 상태 코드 (2001): 200
XML 파싱 성공 (2001)
결과 코드 (2001): None
결과 메시지 (2001): None
응답 상태 코드 (2002): 200
XML 파싱 성공 (2002)
결과 코드 (2002): 00
결과 메시지 (2002): 정상서비스.
응답 상태 코드 (2003): 200
XML 파싱 성공 (2003)
결과 코드 (2003): 00
결과 메시지 (2003): 정상서비스.
응답 상태 코드 (2004): 200
XML 파싱 성공 (2004)
결과 코드 (2004): 00
결과 메시지 (2004): 정상서비스.
응답 상태 코드 (2005): 200
XML 파싱 성공 (2005)
결과 코드 (2005): 00
결과 메시지 (2005): 정상서비스.
응답 상태 코드 (2006): 200
XML 파싱 성공 (2006)
결과 코드 (2006): 00
결과 메시지 (2006): 정상서비스.
응답 상태 코드 (2007): 200
XML 파싱 성공 (2007)
결과 코드 (2007): 00
결과 메시지 (2007): 정상서비스.
응답 상태 코드 (2008): 200
XML 파싱 성공 (2008)
결과 코드 (2008): 00
결과 메시지 (2008): 정상서비스.
응답 상태 코드 (2009): 200
XML 파싱 성공 (2009)
결과 코드 (2009): 00
결과 메시지 (2009): 정상서비스.
응답 상태 코드 (2010): 200
XML 파싱 성공 (2010)
결과 코드 (2010): 00
결과 메시지 (2010): 정상서비스.
응답 상태 코드 (2011): 200
XML 파싱 성공 (2011)
결과 코드 (2011): 00
결과 메시지 (2011): 정상서비스.
응답 상태 코드 (2012): 200
XML 파싱 성공 (2012)
결과 코드 (2012): 00
결과 메시지 (2012): 정상서비스.
응답 상태 코드 (2013): 200
XML 파싱 성공 (2013)
결과 코드 (2013): 00
결과 메시지 (2013): 정상서비스.
응답 상태 코드 (2014): 200
XML 파싱 성공 (2014)
결과 코드 (2014): 00
결과 메시지 (2014): 정상서비스.
응답 상태 코드 (2015): 200
XML 파싱 성공 (2015)
결과 코드 (2015): 00
결과 메시지 (2015): 정상서비스.
응답 상태 코드 (2016): 200
XML 파싱 성공 (2016)
결과 코드 (2016): 00
결과 메시지 (2016): 정상서비스.
응답 상태 코드 (2017): 200
XML 파싱 성공 (2017)
결과 코드 (2017): 00
결과 메시지 (2017): 정상서비스.
응답 상태 코드 (2018): 200
XML 파싱 성공 (2018)
결과 코드 (2018): 00
결과 메시지 (2018): 정상서비스.
응답 상태 코드 (2019): 200
XML 파싱 성공 (2019)
결과 코드 (2019): 00
결과 메시지 (2019): 정상서비스.
응답 상태 코드 (2020): 200
XML 파싱 성공 (2020)
결과 코드 (2020): 00
결과 메시지 (2020): 정상서비스.
응답 상태 코드 (2021): 200
XML 파싱 성공 (2021)
결과 코드 (2021): 00
결과 메시지 (2021): 정상서비스.
응답 상태 코드 (2022): 200
XML 파싱 성공 (2022)
결과 코드 (2022): 00
결과 메시지 (2022): 정상서비스.
응답 상태 코드 (2023): 200
XML 파싱 성공 (2023)
결과 코드 (2023): 00
결과 메시지 (2023): 정상서비스.
          년도       HS 코드                            품목 수출 달러 수출 무게  수입 달러  \
0    2002.01  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0  32800
1    2002.04  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0     71
2    2002.10  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0   6700
3    2002.12  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)  6000   190  42000
4         총계           -                             -  6000   190  81571
..       ...         ...                           ...   ...   ...    ...
102  2023.04  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0     41
103  2023.05  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0    323
104  2023.08  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0   8699
105  2023.11  5001000000  누에고치(생사를 뽑는 데에 적합한 것으로 한정한다)     0     0     50
106       총계           -                             -     0     0  11680

     수입 무게      수지
0     4000  -32800
1        0     -71
2     1000   -6700
3     5250  -36000
4    10250  -75571
..     ...     ...
102      2     -41
103     15    -323
104    200   -8699
105      5     -50
106    272  -11680

[107 rows x 8 columns]

In [26]:
df

,년도,HS 코드,품목,수출 달러,수출 무게,수입 달러,수입 무게,수지
0,2002.01,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,32800,4000,-32800
1,2002.04,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,71,0,-71
2,2002.10,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,6700,1000,-6700
3,2002.12,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),6000,190,42000,5250,-36000
4,총계,-,-,6000,190,81571,10250,-75571
...,...,...,...,...,...,...,...,...
102,2023.04,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,41,2,-41
103,2023.05,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,323,15,-323
104,2023.08,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,8699,200,-8699
105,2023.11,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,50,5,-50
106,총계,-,-,0,0,11680,272,-11680

In [30]:
df = df[df['품목'] != '총계']

In [31]:
df

,년도,HS 코드,품목,수출 달러,수출 무게,수입 달러,수입 무게,수지
0,2002.01,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,32800,4000,-32800
1,2002.04,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,71,0,-71
2,2002.10,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,6700,1000,-6700
3,2002.12,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),6000,190,42000,5250,-36000
4,총계,-,-,6000,190,81571,10250,-75571
...,...,...,...,...,...,...,...,...
102,2023.04,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,41,2,-41
103,2023.05,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,323,15,-323
104,2023.08,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,8699,200,-8699
105,2023.11,5001000000,누에고치(생사를 뽑는 데에 적합한 것으로 한정한다),0,0,50,5,-50
106,총계,-,-,0,0,11680,272,-11680